### ISSUE TITLE
Error enabling SkQuery

### ISSUE THREAD

**Issue by LeCraft2Ouf** [SkQuery/SkQuery#132] opened 2023-02-20 14:14 UTC
Paper version: git-Paper-406 (MC: 1.19.3)
SkQuery version 4.1.8

`[14:56:45 INFO]: [SkQuery] Enabling SkQuery v4.1.8
[14:56:45 ERROR]: Error occurred while enabling SkQuery v4.1.8 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at io.papermc.paper.plugin.provider.util.DummyBukkitPluginLoader.getPluginDescription(DummyBukkitPluginLoader.java:38) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.w00tmast3r.skquery.Registration.enableSnooper(Registration.java:42) ~[SkQuery-4.1.8.jar:?]
        at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:33) ~[SkQuery-4.1.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-406]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-406]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:56:45 INFO]: [SkQuery] Disabling SkQuery v4.1.8
[14:56:45 ERROR]: Error occurred (in the plugin loader) while disabling SkQuery v4.1.8 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.w00tmast3r.skquery.SkQuery.onDisable(SkQuery.java:45) ~[SkQuery-4.1.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.3.jar:git-Paper-406]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[paper-1.19.3.jar:git-Paper-406]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-406]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:207) ~[paper-1.19.3.jar:git-Paper-406]
        at com.w00tmast3r.skquery.elements.events.EvtLambdaWhen.<clinit>(EvtLambdaWhen.java:24) ~[SkQuery-4.1.8.jar:?]
        ... 16 more`

**Comment by takatalvi** [comment] 2023-02-21 09:24
I'm getting this too after updating to the latest Paper. I think it has something to do with build #405, there is a new functionality which I have yet to understand, but it's documented here: https://github.com/PaperMC/Paper/pull/8108

**Comment by MiniDigger** [comment] 2023-02-21 09:48
try paper #409

**Comment by takatalvi** [comment] 2023-02-21 09:57
I actually went from #404 to #409 today, so it's there too. The error must have been caused by a release between these two. As a layman, my best guess is #405, but it might be something higher up. Not sure if this is something Paper needs to patch, or if plugins have to be aligned to it.

**Comment by MiniDigger** [comment] 2023-02-21 12:04
I asked because #409 was pushed in order to iron out a few issues in #405 when we landed the new paper plugin api

this code looks really strange to me https://github.com/SkQuery/SkQuery/blob/master/src/main/java/com/w00tmast3r/skquery/Registration.java#L42
why don't you call JavaPlugin#getDescription instead of all that?
the way you scan the jar file is also really strange (and inefficient)

**Comment by LeCraft2Ouf** [comment] 2023-02-21 16:02
So if I understand correctly, no solution yet?

**Comment by takatalvi** [comment] 2023-02-22 08:20
Not yet, and it's also behaving the same way on Paper #413

**Comment by LeCraft2Ouf** [comment] 2023-02-22 12:06
Yes I saw but is Paper the problem or SkQuery?

**Comment by electronicboy** [comment] 2023-02-26 08:03
This is a paper issue, but, the PluginLoader stuff is deprecated (Nobody really used it, and it was generally in the way of refactoring stuff so that plugin loading can be properly handled and supported before the Server instance is available, i.e. think modifying the registry for stuff like custom biomes, etc);
I probably won't be at my desk for a few days to be able to shove a fix for this, but, do suggest that skquery migrates away from using the PluginLoader

**Comment by TheLimeGlass** [comment] 2023-03-25 06:29
Fixed in 4.1.9

**Closed by TheLimeGlass** 2023-03-25 06:29 UTC

**Comment by TheLimeGlass** [comment] 2023-03-25 06:32
@electronicboy @MiniDigger I just maintain. The methods were switched to getDescription. This plugin is literally from 2012. `JavaPlugin#getPluginLoader().getPluginDescription(src)` is not deprecated. You guys really can't be breaking these things.
